export const newsData = [
  {
    id: 1,
    title: "TÁO ĐEN HỮU CƠ ORGANICLIFE",
    date: "14/02/2025",
    content: "Táo đen hữu cơ OrganicLife quy trình chuẩn tạo nên chất lượng...",
    image: "src/assets/tao-den.webp",
  },
  {
    id: 2,
    title: "LÀM THẾ NÀO ĐỂ BẢO QUẢN BƠ LÂU HƠN?",
    date: "25/03/2025",
    content: "Bơ là loại trái cây bổ dưỡng nhưng dễ hỏng nếu không bảo quản đúng cách...",
    image: "src/assets/bo.jpg",
  },
  {
    id: 3,
    title: "LỢI ÍCH CỦA TÁO ĐỎ ĐỐI VỚI SỨC KHỎE",
    date: "05/03/2025",
    content: "Táo đỏ chứa nhiều chất chống oxy hóa và giúp tăng cường hệ miễn dịch...",
    image: "src/assets/2e38c1cb-4723-4e90-b871-c58d21e6ba9e.webp",
  },
  {
    id: 4,
    title: "LỰU – BÍ QUYẾT GIÚP LÀM ĐẸP DA TỪ THIÊN NHIÊN",
    date: "02/04/2025",
    content: "Nước ép lựu giúp chống lão hóa và mang lại làn da sáng mịn...",
    image: "src/assets/luu.webp",
  },
  {
    id: 5,
    title: "CAM – NGUỒN VITAMIN C TỰ NHIÊN TUYỆT VỜI",
    date: "15/04/2025",
    content: "Cam giúp tăng cường sức đề kháng và giảm căng thẳng hiệu quả...",
    image: "src/assets/cam.webp",
  },
  {
    id: 6,
    title: "TẾT NÀY TẶNG NHAU QUÀ GÌ?",
    date: "27/12/2024",
    content: "Tết này tặng nhau quà gì? Không chỉ đơn giản là tặng một món quà...",
    image: "src/assets/thuan2.png",
  },
  {
    id: 7,
    title: "NÊN ĂN CHUỐI VÀO LÚC NÀO LÀ TỐT NHẤT?",
    date: "12/03/2025",
    content: "Chuối giúp cung cấp năng lượng và hỗ trợ tiêu hóa hiệu quả...",
    image: "src/assets/Chuoi.webp",
  },
  {
    id: 8,
    title: "XOÀI CHÍN VÀ NHỮNG LỢI ÍCH KHÔNG NGỜ",
    date: "10/04/2025",
    content: "Xoài không chỉ ngon mà còn giúp cải thiện tiêu hóa và tăng cường thị lực...",
    image: "src/assets/xoai.jpg",
  },
  {
    id: 9,
    title: "DÂU TÂY – LOẠI TRÁI CÂY CHỐNG LÃO HÓA TUYỆT VỜI",
    date: "18/03/2025",
    content: "Dâu tây giàu vitamin C giúp da luôn tươi trẻ và sáng mịn...",
    image: "src/assets/Strawberry1.png",
  },
];